import { create } from 'zustand';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type LanguageCode = 'en' | 'es' | 'fr' | 'de' | 'hi' | 'ja' | 'ko';

export interface LanguageInfo {
  code: LanguageCode;
  label: string;
  nativeLabel: string;
}

export const LANGUAGES: LanguageInfo[] = [
  { code: 'en', label: 'English', nativeLabel: 'English' },
  { code: 'es', label: 'Spanish', nativeLabel: 'Español' },
  { code: 'fr', label: 'French', nativeLabel: 'Français' },
  { code: 'de', label: 'German', nativeLabel: 'Deutsch' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिन्दी' },
  { code: 'ja', label: 'Japanese', nativeLabel: '日本語' },
  { code: 'ko', label: 'Korean', nativeLabel: '한국어' },
];

export const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Navigation / Tabs
    'tab.home': 'Home',
    'tab.explore': 'Explore',
    'tab.aiChat': 'Cine AI',
    'tab.saved': 'Saved',
    'tab.profile': 'Profile',
    
    // Homepage
    'home.greeting.morning': 'Good Morning',
    'home.greeting.afternoon': 'Good Afternoon',
    'home.greeting.evening': 'Good Evening',
    'home.brand.ai': 'AI',
    'home.searchPlaceholder': 'Search movies, genres...',
    'home.section.continue': 'Continue Watching',
    'home.section.continueSub': 'From your watch history',
    'home.section.ai': 'AI Recommendations',
    'home.section.aiSub': 'Curated high-confidence picks',
    'home.section.mood': 'Mood Discovery',
    'home.section.moodSub': 'Tap a mood to generate a live TMDB rail',
    
    // Search
    'search.title': 'Search',
    'search.placeholder': 'Find movies, directors, actors...',
    'search.filters': 'Filters',
    'search.noResults': 'No movies found matching your request.',
    'search.back': 'Back',

    // AI Chat
    'chat.welcomeTitle': 'What should we watch?',
    'chat.welcomeSub': 'Ask for a mood, director, genre, hidden gem, or a custom shortlist.',
    'chat.inputPlaceholder': 'Ask CineAI what to watch...',
    'chat.status.listening': 'Listening...',
    'chat.status.online': 'Online',
    'chat.status.fallback': 'Fallback',
    'chat.status.local': 'Local recovery active',
    'chat.status.quick': 'Quick AI',
    'chat.starter.mood': 'Match my mood',
    'chat.starter.moodPrompt': 'I want something atmospheric, emotional, and beautifully shot for tonight.',
    'chat.starter.surprise': 'Surprise me',
    'chat.starter.surprisePrompt': 'Recommend movies I might not expect to love, but probably will.',
    'chat.starter.prestige': 'Prestige picks',
    'chat.starter.prestigePrompt': 'Give me award-worthy films with excellent writing and performances.',
    'chat.starter.thrill': 'High tension',
    'chat.starter.thrillPrompt': 'Find a tense thriller that grabs attention from the first scene.',
    'chat.starter.worlds': 'Worldbuilding',
    'chat.starter.worldsPrompt': 'Suggest immersive sci-fi or fantasy worlds with strong cinematic scale.',
    'chat.starter.hidden': 'Hidden gems',
    'chat.starter.hiddenPrompt': 'Show me underrated films with a strong emotional payoff.',
    'chat.history': 'Chat History',
    'chat.historySub': 'Resume a conversation or clear old threads.',
    'chat.historyEmpty': 'No conversations yet.',
    'rail.trending-worldwide.title': 'Trending Worldwide',
    'rail.trending-worldwide.subtitle': 'The most discussed films right now',
    'rail.trending-india.title': 'Trending in India',
    'rail.trending-india.subtitle': 'Regional momentum and crowd favorites',
    'rail.hollywood-scifi.title': 'Hollywood Sci-Fi',
    'rail.hollywood-scifi.subtitle': 'Large-scale futures and speculative worlds',
    'rail.award-winners.title': 'Award Winners',
    'rail.award-winners.subtitle': 'Celebrated films from global awards circuits',
    'rail.hidden-gems.title': 'Hidden Gems',
    'rail.hidden-gems.subtitle': 'Highly rated films outside mainstream cycles',
    
    // Profile Main
    'profile.title': 'Entertainment Identity',
    'profile.badge.premium': 'Premium Pass',
    'profile.badge.guest': 'Guest User',
    'profile.stat.saved': 'Saved',
    'profile.stat.chats': 'AI Chats',
    'profile.stat.genres': 'Genres',
    'profile.taste.title': 'AI Taste Profile',
    'profile.taste.default': 'Your AI taste profile grows as you explore and chat with CineAI.',
    'profile.section.account': 'Account Ecosystem',
    'profile.section.preferences': 'Cinematic Preferences',
    'profile.section.support': 'Support Desk',
    
    // Profile Rows
    'profile.row.editProfile': 'Edit Profile',
    'profile.row.notifications': 'Notifications Hub',
    'profile.row.language': 'Language Settings',
    'profile.row.genres': 'Favorite Genres',
    'profile.row.aiPersonality': 'AI Personality Mode',
    'profile.row.region': 'Content Region',
    'profile.row.faq': 'Help Center & FAQ',
    'profile.row.privacy': 'Privacy Policy',
    'profile.row.terms': 'Terms of Service',
    'profile.row.signOut': 'Sign Out',
    'profile.row.signOutSub': 'End this secure CineAI session',
    'profile.version': 'CineAI v3.0 — Powered by Gemma 4',

    // Edit Profile Panel
    'edit.title': 'Edit Profile',
    'edit.fullName': 'Full Name',
    'edit.username': 'Username',
    'edit.password': 'Password',
    'edit.newPassword': 'New Password (leave empty to keep current)',
    'edit.save': 'Save Changes',
    'edit.saving': 'Saving...',
    'edit.success': 'Profile updated successfully!',
    'edit.errName': 'Name must be at least 2 characters.',
    'edit.errUsername': 'Username must be at least 3 characters.',
    'edit.errPassword': 'Password must be at least 6 characters.',

    // Notifications Panel
    'notif.title': 'Notifications Hub',
    'notif.desc': 'Control when CineAI updates you with fresh cinematic recommendations and updates.',
    'notif.rec': 'New Recommendations',
    'notif.recDesc': 'Get custom, high-confidence movie selections.',
    'notif.trending': 'Trending Content Alerts',
    'notif.trendingDesc': 'Stay updated with global box office breakouts.',
    'notif.upcoming': 'Upcoming Releases',
    'notif.upcomingDesc': 'Be notified when your anticipated movies release.',
    'notif.ai': 'AI recommendation updates',
    'notif.aiDesc': 'Get pinged when your AI taste profile evolves.',
    'notif.watchlist': 'Watchlist reminders',
    'notif.watchlistDesc': 'Receive gentle nudges to watch saved movies.',
    'notif.alerts': 'New Content Alerts',
    'notif.alertsDesc': 'Receive instant alerts on new platform entries.',

    // Language Panel
    'lang.title': 'Language Settings',
    'lang.desc': 'Change the global language of the user interface, search query logs, and chatbot prompts.',

    // Genres Panel
    'genres.title': 'Favorite Genres',
    'genres.desc': 'Select your preferred genres. These choices guide the AI recommendation rails, search relevance, and chatbot personalities.',
    'genres.save': 'Save Genres',

    // AI Personality Panel
    'personality.title': 'AI Personality Mode',
    'personality.desc': 'Choose the style and tone of the CineAI conversational chatbot companion.',
    'personality.critic.name': 'Cinematic Critic',
    'personality.critic.desc': 'Warm, highly specific, opinionated critic who highlights direction, cinematography, and script depth.',
    'personality.friend.name': 'Casual Friend',
    'personality.friend.desc': 'Relaxed, friendly, non-pretentious friend giving fun recommendations over popcorn.',
    'personality.expert.name': 'Film Expert',
    'personality.expert.desc': 'Deep academic cinema nerd detailing historical context, film theories, and deep hidden connections.',
    'personality.hype.name': 'Hype Recommender',
    'personality.hype.desc': 'High-energy, super excited cinephile showcasing adrenaline-fueled blockbusters and high-tension thrillers.',
    'personality.companion.name': 'Chill Companion',
    'personality.companion.desc': 'Comforting, thoughtful guide recommending cozy, emotional, and comforting watchlists.',
    'personality.nerd.name': 'Dark Cinema Nerd',
    'personality.nerd.desc': 'Atmospheric, gothic-inspired film geek recommending deep, gritty, indie thrillers, and psychological horrors.',

    // Region Panel
    'region.title': 'Content Region',
    'region.desc': 'Influences trending content relevance, box office popularity metrics, and localized recommendations.',
    'region.global': 'Global',
    'region.us': 'United States',
    'region.in': 'India',
    'region.jp': 'Japan',
    'region.kr': 'South Korea',

    // FAQ Panel
    'faq.title': 'Help Center & FAQ',
    'faq.search': 'Search help topics...',
    'faq.q1': 'What are the CineAI Online/Offline states?',
    'faq.a1': 'CineAI includes a highly resilient multi-mode architecture. When the primary high-performance cloud server is fully awake, you receive premium, instant responses with live streaming availability. If the connection fails or Render spins down, CineAI seamlessly activates a robust local offline AI fallback system, so you never lose conversational access.',
    'faq.q2': 'Why do my movie recommendations change?',
    'faq.a2': 'Your recommendations dynamically adapt based on three parameters: your selected Favorite Genres, your active Content Region, and your real conversational history with CineAI. As you chat, save items to your Watchlist, or update your preferences, CineAI refines your recommendations rail instantly.',
    'faq.q3': 'How does the offline AI fallback work?',
    'faq.a3': 'If our cloud APIs time out or return an error (such as a 502 Bad Gateway), the mobile client immediately triggers our local recovery system. This lets you browse cached recommendations, interact with preloaded datasets, and receive secure offline suggestions without interruptions.',
    'faq.q4': 'Where does the trailer information come from?',
    'faq.a4': 'Trailers are fetched dynamically by consolidating official IMDB IDs with active TMDB media channels. If a trailer is available, a Play button appears instantly on the Movie Details banner. If no official video is found, a general YouTube search query is fallback mapped.',
    'faq.q5': 'Does my watchlist sync across devices?',
    'faq.a5': 'Yes! If you are signed in, your Watchlist, chat threads, and personalized cinematic profile are synchronized in real-time with our secure Supabase database. Guest sessions are stored locally in your device storage and can be migrated upon registering a secure account.',
    'faq.q6': 'What are the limits of Guest Mode?',
    'faq.a6': 'Guest Mode allows you to browse the homepage, explore collections, search, and chat with CineAI. However, since there is no persistent account profile, your watchlists and conversation history are kept locally in the cache and will be lost if you clear app storage or switch devices.',
    'faq.q7': 'How does the voice assistant work?',
    'faq.a7': 'Tap the microphone icon in the AI Chat screen to dictate your prompts. Speech-to-text recognition will turn your voice input into a typed prompt. (Note: voice input requires microphone permissions and is supported in custom development builds).',

    // Support Panel
    'support.title': 'CineAI Support Desk',
    'support.contact': 'Contact Support',
    'support.report': 'Report a Problem',
    'support.feedback': 'Submit Feedback',
    'support.desc': 'Our support team is here to assist you. Select a category below to submit a secure request directly to our developers.',
    'support.email': 'Your Email Address',
    'support.subject': 'Subject',
    'support.message': 'Message details',
    'support.submit': 'Submit Ticket',
    'support.submitting': 'Sending...',
    'support.success': 'Your request has been securely submitted! We will reach out shortly.',
    'support.error': 'Please fill out all fields correctly.',
    'support.legalTitle': 'Legal & Policy Center',
    'support.privacyDesc': 'Your privacy is extremely important. CineAI operates under strict privacy protections: sensitive API keys live securely in the cloud, all chat history is securely encrypted, and we never share your TMDB search trends or personal watch preferences with third parties. You can request a complete profile deletion at any time.',
    'support.termsDesc': 'By using CineAI, you agree to utilize our AI recommendations and chatbot engine for personal entertainment purposes. You agree not to abuse or flood our API endpoints, which are rate-limited via built-in SlowAPI telemetry. All content descriptions and trailers are aggregated courtesy of TMDB.',
    
    // Auth / Onboarding
    'auth.guestUpgrade': 'Upgrade to Premium Account',
    'auth.guestUpgradeSub': 'Create a secure account to sync watchlist & chats.',
  },
  es: {
    // Navigation / Tabs
    'tab.home': 'Inicio',
    'tab.explore': 'Explorar',
    'tab.aiChat': 'Cine AI',
    'tab.saved': 'Guardado',
    'tab.profile': 'Perfil',
    
    // Homepage
    'home.greeting.morning': 'Buenos Días',
    'home.greeting.afternoon': 'Buenas Tardes',
    'home.greeting.evening': 'Buenas Noches',
    'home.brand.ai': 'IA',
    'home.searchPlaceholder': 'Buscar películas, géneros...',
    'home.section.continue': 'Continuar Viendo',
    'home.section.continueSub': 'De tu historial de reproducción',
    'home.section.ai': 'Recomendaciones de IA',
    'home.section.aiSub': 'Selecciones de alta confianza',
    'home.section.mood': 'Descubrimiento de Ánimo',
    'home.section.moodSub': 'Toca un ánimo para generar una lista de TMDB',
    
    // Search
    'search.title': 'Buscar',
    'search.placeholder': 'Buscar películas, directores...',
    'search.filters': 'Filtros',
    'search.noResults': 'No se encontraron películas para tu búsqueda.',
    'search.back': 'Volver',

    // AI Chat
    'chat.welcomeTitle': '¿Qué vemos hoy?',
    'chat.welcomeSub': 'Pide un estado de ánimo, director, género o lista personalizada.',
    'chat.inputPlaceholder': 'Pregúntale a CineAI qué ver...',
    'chat.status.listening': 'Escuchando...',
    'chat.status.online': 'En Línea',
    'chat.status.fallback': 'Alternativo',
    'chat.status.local': 'Recuperación local activa',
    'chat.status.quick': 'IA Rápida',
    'chat.starter.mood': 'Mi estado de ánimo',
    'chat.starter.moodPrompt': 'Quiero algo atmosférico, emocional y hermosamente filmado para esta noche.',
    'chat.starter.surprise': 'Sorpréndeme',
    'chat.starter.surprisePrompt': 'Recomienda películas que quizás no espere amar, pero que probablemente me encanten.',
    'chat.starter.prestige': 'Selecciones prestigiosas',
    'chat.starter.prestigePrompt': 'Dame películas dignas de premios con excelentes actuaciones y guiones.',
    'chat.starter.thrill': 'Alta tensión',
    'chat.starter.thrillPrompt': 'Busca un thriller tenso que capte la atención desde la primera escena.',
    'chat.starter.worlds': 'Construcción de mundos',
    'chat.starter.worldsPrompt': 'Sugiere mundos de ciencia ficción o fantasía inmersivos a gran escala.',
    'chat.starter.hidden': 'Joyas ocultas',
    'chat.starter.hiddenPrompt': 'Muéstrame películas subestimadas con un gran final emocional.',
    'chat.history': 'Historial de Chats',
    'chat.historySub': 'Reanuda una conversación o borra hilos antiguos.',
    'chat.historyEmpty': 'Aún no hay conversaciones.',
    'rail.trending-worldwide.title': 'Tendencias Mundiales',
    'rail.trending-worldwide.subtitle': 'Las películas más comentadas del momento',
    'rail.trending-india.title': 'Tendencias en India',
    'rail.trending-india.subtitle': 'Éxitos regionales y favoritos del público',
    'rail.hollywood-scifi.title': 'Ciencia Ficción',
    'rail.hollywood-scifi.subtitle': 'Futuros a gran escala y mundos especulativos',
    'rail.award-winners.title': 'Ganadoras de Premios',
    'rail.award-winners.subtitle': 'Películas celebradas en circuitos de premios globales',
    'rail.hidden-gems.title': 'Joyas Ocultas',
    'rail.hidden-gems.subtitle': 'Películas muy valoradas fuera del circuito comercial',

    // Profile Main
    'profile.title': 'Identidad de Entretenimiento',
    'profile.badge.premium': 'Pase Premium',
    'profile.badge.guest': 'Invitado',
    'profile.stat.saved': 'Guardado',
    'profile.stat.chats': 'Chats IA',
    'profile.stat.genres': 'Géneros',
    'profile.taste.title': 'Perfil de Gusto IA',
    'profile.taste.default': 'Tu perfil de gusto IA crece a medida que exploras y chateas con CineAI.',
    'profile.section.account': 'Ecosistema de Cuenta',
    'profile.section.preferences': 'Preferencias Cinematográficas',
    'profile.section.support': 'Soporte Técnico',
    
    // Profile Rows
    'profile.row.editProfile': 'Editar Perfil',
    'profile.row.notifications': 'Notificaciones',
    'profile.row.language': 'Ajustes de Idioma',
    'profile.row.genres': 'Géneros Favoritos',
    'profile.row.aiPersonality': 'Personalidad de IA',
    'profile.row.region': 'Región de Contenido',
    'profile.row.faq': 'Centro de Ayuda y FAQ',
    'profile.row.privacy': 'Política de Privacidad',
    'profile.row.terms': 'Términos de Servicio',
    'profile.row.signOut': 'Cerrar Sesión',
    'profile.row.signOutSub': 'Terminar esta sesión segura de CineAI',
    'profile.version': 'CineAI v3.0 — Potenciado por Gemma 4',

    // Edit Profile Panel
    'edit.title': 'Editar Perfil',
    'edit.fullName': 'Nombre Completo',
    'edit.username': 'Nombre de Usuario',
    'edit.password': 'Contraseña',
    'edit.newPassword': 'Nueva contraseña (vacío para mantener actual)',
    'edit.save': 'Guardar Cambios',
    'edit.saving': 'Guardando...',
    'edit.success': '¡Perfil actualizado con éxito!',
    'edit.errName': 'El nombre debe tener al menos 2 caracteres.',
    'edit.errUsername': 'El usuario debe tener al menos 3 caracteres.',
    'edit.errPassword': 'La contraseña debe tener al menos 6 caracteres.',

    // Notifications Panel
    'notif.title': 'Centro de Notificaciones',
    'notif.desc': 'Controla cuándo CineAI te actualiza con recomendaciones cinematográficas frescas y novedades.',
    'notif.rec': 'Nuevas Recomendaciones',
    'notif.recDesc': 'Recibe selecciones personalizadas de alta confianza.',
    'notif.trending': 'Alertas de Tendencias',
    'notif.trendingDesc': 'Mantente al día con los éxitos mundiales de taquilla.',
    'notif.upcoming': 'Próximos Estrenos',
    'notif.upcomingDesc': 'Recibe notificaciones cuando se estrenen tus películas esperadas.',
    'notif.ai': 'Actualizaciones de Gusto IA',
    'notif.aiDesc': 'Recibe un aviso cuando tu perfil de gusto IA evolucione.',
    'notif.watchlist': 'Recordatorios de Guardados',
    'notif.watchlistDesc': 'Nudistas sutiles para ver tus películas guardadas.',
    'notif.alerts': 'Alertas de Contenido Nuevo',
    'notif.alertsDesc': 'Recibe alertas instantáneas sobre nuevas entradas.',

    // Language Panel
    'lang.title': 'Ajustes de Idioma',
    'lang.desc': 'Cambia el idioma global de la interfaz de usuario, búsquedas y el chat de IA.',

    // Genres Panel
    'genres.title': 'Géneros Favoritos',
    'genres.desc': 'Selecciona tus géneros preferidos. Estas elecciones guían las sugerencias de la IA y el chat.',
    'genres.save': 'Guardar Géneros',

    // AI Personality Panel
    'personality.title': 'Personalidad de IA',
    'personality.desc': 'Elige el estilo y tono de tu compañero de chat CineAI.',
    'personality.critic.name': 'Crítico de Cine',
    'personality.critic.desc': 'Cálido, muy específico, crítico opinativo que destaca la dirección, fotografía y guion.',
    'personality.friend.name': 'Amigo Casual',
    'personality.friend.desc': 'Amigo relajado y sin pretensiones que da recomendaciones divertidas mientras comen palomitas.',
    'personality.expert.name': 'Experto en Cine',
    'personality.expert.desc': 'Cinefilia académica profunda que detalla el contexto histórico, teorías y conexiones ocultas.',
    'personality.hype.name': 'Entusiasta Enérgico',
    'personality.hype.desc': 'Cinefilo lleno de energía que destaca películas de acción y thrillers de alta tensión.',
    'personality.companion.name': 'Compañero Relajado',
    'personality.companion.desc': 'Guía cálida y reflexiva que recomienda listas acogedoras y reconfortantes.',
    'personality.nerd.name': 'Cinefilo Oscuro',
    'personality.nerd.desc': 'Friki de cine atmosférico y gótico que recomienda thrillers psicológicos y terror indie.',

    // Region Panel
    'region.title': 'Región de Contenido',
    'region.desc': 'Influye en la relevancia de las tendencias y las recomendaciones localizadas.',
    'region.global': 'Global',
    'region.us': 'Estados Unidos',
    'region.in': 'India',
    'region.jp': 'Japón',
    'region.kr': 'Corea del Sur',

    // FAQ Panel
    'faq.title': 'Centro de Ayuda y FAQ',
    'faq.search': 'Buscar temas de ayuda...',
    'faq.q1': '¿Qué son los estados de CineAI?',
    'faq.a1': 'CineAI incluye una arquitectura multi-modo altamente resiliente. Cuando el servidor principal está despierto, disfrutas de respuestas instantáneas con disponibilidad en streaming. Si falla la red, CineAI activa un sistema local offline para que nunca pierdas el chat.',
    'faq.q2': '¿Por qué cambian mis recomendaciones?',
    'faq.a2': 'Tus recomendaciones se adaptan a tus géneros favoritos, región y chat. A medida que guardas películas o hablas con la IA, CineAI se actualiza al instante.',
    'faq.q3': '¿Cómo funciona la IA offline?',
    'faq.a3': 'Si la API en la nube falla (por ejemplo, error 502), el cliente móvil activa la recuperación local. Esto te permite ver recomendaciones guardadas y recibir sugerencias preconfiguradas.',
    'faq.q4': '¿De dónde vienen los tráilers?',
    'faq.a4': 'Los tráilers se buscan usando códigos de IMDB en TMDB. Si hay tráiler disponible, verás un botón de reproducir. Si no, busca en YouTube.',
    'faq.q5': '¿Se sincroniza mi lista entre dispositivos?',
    'faq.a5': '¡Sí! Si tienes una cuenta, tus datos se guardan en Supabase. Si usas modo invitado, se guardan en el dispositivo.',
    'faq.q6': '¿Cuáles son los límites de Invitado?',
    'faq.a6': 'Puedes explorar y usar el chat de IA. Sin embargo, tus datos se perderán si borras la app o cambias de móvil.',
    'faq.q7': '¿Cómo funciona el asistente de voz?',
    'faq.a7': 'Toca el micrófono en el chat para dictar. La app convertirá tu voz en texto (requiere permisos de micrófono).',

    // Support Panel
    'support.title': 'Soporte CineAI',
    'support.contact': 'Contacto',
    'support.report': 'Reportar Problema',
    'support.feedback': 'Enviar Comentarios',
    'support.desc': 'El equipo de soporte está aquí para ayudarte. Rellena los datos para contactar con los desarrolladores.',
    'support.email': 'Tu Correo Electrónico',
    'support.subject': 'Asunto',
    'support.message': 'Detalles del Mensaje',
    'support.submit': 'Enviar Ticket',
    'support.submitting': 'Enviando...',
    'support.success': '¡Tu ticket ha sido enviado! Nos pondremos en contacto pronto.',
    'support.error': 'Por favor rellena todos los campos correctamente.',
    'support.legalTitle': 'Centro Legal',
    'support.privacyDesc': 'Tu privacidad es lo primero. CineAI no comparte tus datos de búsqueda ni tus preferencias de visualización con terceros.',
    'support.termsDesc': 'Al usar CineAI, aceptas usar nuestras recomendaciones para fines personales de entretenimiento. Las APIS están protegidas contra saturaciones.',
    
    // Auth / Onboarding
    'auth.guestUpgrade': 'Mejorar a Cuenta Premium',
    'auth.guestUpgradeSub': 'Crea una cuenta para guardar historial y listas.',
  },
  // French Translation
  fr: {
    'tab.home': 'Accueil',
    'tab.explore': 'Explorer',
    'tab.aiChat': 'Cine AI',
    'tab.saved': 'Enregistré',
    'tab.profile': 'Profil',
    'home.greeting.morning': 'Bon matin',
    'home.greeting.afternoon': 'Bon après-midi',
    'home.greeting.evening': 'Bonsoir',
    'home.brand.ai': 'IA',
    'home.searchPlaceholder': 'Rechercher des films, genres...',
    'home.section.continue': 'Reprendre la lecture',
    'home.section.continueSub': 'De votre historique',
    'home.section.ai': 'Recommandations IA',
    'home.section.aiSub': 'Sélections haute fidélité',
    'home.section.mood': 'Découverte d\'ambiance',
    'home.section.moodSub': 'Tapez sur une ambiance pour générer un rail',
    'search.title': 'Recherche',
    'search.placeholder': 'Films, réalisateurs, acteurs...',
    'search.filters': 'Filtres',
    'search.noResults': 'Aucun film ne correspond à votre recherche.',
    'search.back': 'Retour',
    'chat.welcomeTitle': 'Qu\'est-ce qu\'on regarde ?',
    'chat.welcomeSub': 'Demandez un réalisateur, un genre, ou une liste personnalisée.',
    'chat.inputPlaceholder': 'Demander à CineAI quoi regarder...',
    'chat.status.listening': 'Écoute...',
    'chat.status.online': 'En ligne',
    'chat.status.fallback': 'Secours',
    'chat.status.local': 'Récupération locale active',
    'chat.status.quick': 'IA Rapide',
    'chat.starter.mood': 'Selon mon humeur',
    'chat.starter.moodPrompt': 'Je veux quelque chose d\'atmosphérique et d\'émouvant ce soir.',
    'chat.starter.surprise': 'Surprends-moi',
    'chat.starter.surprisePrompt': 'Recommande-moi des films inattendus que je vais adorer.',
    'chat.starter.prestige': 'Sélection prestige',
    'chat.starter.prestigePrompt': 'Des films acclamés par la critique avec de superbes performances.',
    'chat.starter.thrill': 'Haute tension',
    'chat.starter.thrillPrompt': 'Un thriller tendu qui capte l\'attention dès le début.',
    'chat.starter.worlds': 'Nouveaux mondes',
    'chat.starter.worldsPrompt': 'Suggère des mondes de science-fiction ou de fantasy immersifs.',
    'chat.starter.hidden': 'Pépites cachées',
    'chat.starter.hiddenPrompt': 'Des films sous-estimés avec un fort impact émotionnel.',
    'chat.history': 'Historique des Chats',
    'chat.historySub': 'Reprenez une conversation ou effacez d\'anciens fils.',
    'chat.historyEmpty': 'Aucune conversation pour le moment.',
    'rail.trending-worldwide.title': 'Tendances mondiales',
    'rail.trending-worldwide.subtitle': 'Les films les plus discutés en ce moment',
    'rail.trending-india.title': 'Tendances en Inde',
    'rail.trending-india.subtitle': 'Succès régionaux et favoris du public',
    'rail.hollywood-scifi.title': 'Science-Fiction',
    'rail.hollywood-scifi.subtitle': 'Futurs à grande échelle et mondes spéculatifs',
    'rail.award-winners.title': 'Films primés',
    'rail.award-winners.subtitle': 'Films célébrés dans les circuits de récompenses mondiaux',
    'rail.hidden-gems.title': 'Pépites cachées',
    'rail.hidden-gems.subtitle': 'Films très bien notés en dehors du circuit commercial',
    'profile.title': 'Identité Cinématographique',
    'profile.badge.premium': 'Pass Premium',
    'profile.badge.guest': 'Invité',
    'profile.stat.saved': 'Enregistré',
    'profile.stat.chats': 'Chats IA',
    'profile.stat.genres': 'Genres',
    'profile.taste.title': 'Profil de Goût IA',
    'profile.taste.default': 'Votre profil de goût IA s\'enrichit de vos choix.',
    'profile.section.account': 'Écosystème du Compte',
    'profile.section.preferences': 'Préférences Cinéma',
    'profile.section.support': 'Bureau d\'Assistance',
    'profile.row.editProfile': 'Modifier le Profil',
    'profile.row.notifications': 'Centre de Notifications',
    'profile.row.language': 'Paramètres de Langue',
    'profile.row.genres': 'Genres Préférés',
    'profile.row.aiPersonality': 'Personnalité de l\'IA',
    'profile.row.region': 'Région de Contenu',
    'profile.row.faq': 'FAQ & Centre d\'Aide',
    'profile.row.privacy': 'Politique de Confidentialité',
    'profile.row.terms': 'Conditions d\'Utilisation',
    'profile.row.signOut': 'Déconnexion',
    'profile.row.signOutSub': 'Mettre fin à cette session sécurisée',
    'profile.version': 'CineAI v3.0 — Propulsé par Gemma 4',
    'edit.title': 'Modifier le Profil',
    'edit.fullName': 'Nom Complet',
    'edit.username': 'Nom d\'utilisateur',
    'edit.password': 'Mot de passe',
    'edit.newPassword': 'Nouveau mot de passe (laisser vide pour inchangé)',
    'edit.save': 'Enregistrer',
    'edit.saving': 'Enregistrement...',
    'edit.success': 'Profil mis à jour !',
    'edit.errName': 'Le nom doit faire au moins 2 caractères.',
    'edit.errUsername': 'Le nom d\'utilisateur doit faire au moins 3 caractères.',
    'edit.errPassword': 'Le mot de passe doit faire au moins 6 caractères.',
    'notif.title': 'Notifications',
    'notif.desc': 'Gérez les alertes et les mises à jour de CineAI.',
    'notif.rec': 'Nouvelles Recommandations',
    'notif.recDesc': 'Sélections de films personnalisées par l\'IA.',
    'notif.trending': 'Alertes Tendances',
    'notif.trendingDesc': 'Restez à jour sur les succès du box-office.',
    'notif.upcoming': 'Sorties Attendues',
    'notif.upcomingDesc': 'Alertes de sortie pour vos films attendus.',
    'notif.ai': 'Mises à jour du profil IA',
    'notif.aiDesc': 'Alertes d\'évolution de votre profil de goût IA.',
    'notif.watchlist': 'Rappels de liste',
    'notif.watchlistDesc': 'Rappels pour regarder vos films enregistrés.',
    'notif.alerts': 'Nouvelles Entrées',
    'notif.alertsDesc': 'Alertes lors de l\'ajout de nouveaux contenus.',
    'lang.title': 'Paramètres de Langue',
    'lang.desc': 'Changez la langue globale de l\'application et du chat.',
    'genres.title': 'Genres Préférés',
    'genres.desc': 'Sélectionnez vos genres préférés pour guider les recommandations.',
    'genres.save': 'Enregistrer les Genres',
    'personality.title': 'Personnalité de l\'IA',
    'personality.desc': 'Choisissez le style et le ton du chatbot CineAI.',
    'personality.critic.name': 'Critique Ciné',
    'personality.critic.desc': 'Avis chaleureux et précis sur la réalisation, l\'écriture et le jeu.',
    'personality.friend.name': 'Ami Décontracté',
    'personality.friend.desc': 'Conseils amicaux et sans chichis autour d\'un pop-corn.',
    'personality.expert.name': 'Expert Cinéphile',
    'personality.expert.desc': 'Analyses théoriques profondes, contextes historiques et détails cachés.',
    'personality.hype.name': 'Fou de Ciné',
    'personality.hype.desc': 'Énergie débordante axée sur les blockbusters et le grand spectacle.',
    'personality.companion.name': 'Compagnon Zen',
    'personality.companion.desc': 'Guide bienveillant axé sur les films intimes, réconfortants et profonds.',
    'personality.nerd.name': 'Spécialiste Sombre',
    'personality.nerd.desc': 'Passionné de films d\'auteur sombres, thrillers psychologiques et horreur.',
    'region.title': 'Région de Contenu',
    'region.desc': 'Adapte les tendances et les recommandations à votre zone géographique.',
    'region.global': 'Global',
    'region.us': 'États-Unis',
    'region.in': 'Inde',
    'region.jp': 'Japon',
    'region.kr': 'Corée du Sud',
    'faq.title': 'FAQ & Aide',
    'faq.search': 'Rechercher de l\'aide...',
    'faq.q1': 'Quels sont les états CineAI ?',
    'faq.a1': 'CineAI bascule automatiquement en mode hors ligne si le serveur principal n\'est pas accessible. Vous gardez l\'accès aux fonctionnalités principales.',
    'faq.q2': 'Pourquoi mes recommandations changent ?',
    'faq.a2': 'Les recommandations évoluent avec vos genres préférés, votre région, et vos conversations de chat.',
    'faq.q3': 'Comment fonctionne le mode hors ligne ?',
    'faq.a3': 'En cas de panne réseau (ex. erreur 502), le client bascule sur la base locale pour proposer des suggestions préchargées.',
    'faq.q4': 'D\'où viennent les bandes-annonces ?',
    'faq.a4': 'Les vidéos proviennent de la base TMDB associée aux codes IMDB. Si rien n\'est trouvé, nous basculons sur YouTube.',
    'faq.q5': 'Ma liste est-elle synchronisée ?',
    'faq.a5': 'Oui ! Si vous avez un compte, tout est sauvegardé sur Supabase. Sinon, c\'est conservé localement.',
    'faq.q6': 'Quelles sont les limites du mode Invité ?',
    'faq.a6': 'Vous pouvez parcourir l\'application et chatter, mais vos données seront perdues en cas de changement de téléphone.',
    'faq.q7': 'Comment marche l\'assistant vocal ?',
    'faq.a7': 'Cliquez sur le micro pour dicter vos requêtes (nécessite l\'autorisation d\'accès au microphone).',
    'support.title': 'Support CineAI',
    'support.contact': 'Nous Contacter',
    'support.report': 'Signaler un Problème',
    'support.feedback': 'Laisser un Avis',
    'support.desc': 'Le support client est là pour vous aider. Sélectionnez une catégorie pour envoyer un ticket.',
    'support.email': 'Votre Email',
    'support.subject': 'Sujet',
    'support.message': 'Message',
    'support.submit': 'Envoyer',
    'support.submitting': 'Envoi...',
    'support.success': 'Votre ticket a été envoyé ! Nous vous répondrons bientôt.',
    'support.error': 'Veuillez remplir tous les champs correctement.',
    'support.legalTitle': 'Centre Légal',
    'support.privacyDesc': 'Votre vie privée est notre priorité. Vos requêtes de recherche et listes ne sont jamais partagées.',
    'support.termsDesc': 'En utilisant CineAI, vous acceptez nos conditions d\'utilisation pour un usage personnel uniquement.',
    'auth.guestUpgrade': 'Passer au Compte Premium',
    'auth.guestUpgradeSub': 'Créez un compte pour synchroniser vos listes et chats.',
  },
  // German Translation
  de: {
    'tab.home': 'Start',
    'tab.explore': 'Entdecken',
    'tab.aiChat': 'Cine AI',
    'tab.saved': 'Gespeichert',
    'tab.profile': 'Profil',
    'home.greeting.morning': 'Guten Morgen',
    'home.greeting.afternoon': 'Guten Tag',
    'home.greeting.evening': 'Guten Abend',
    'home.brand.ai': 'KI',
    'home.searchPlaceholder': 'Filme, Genres suchen...',
    'home.section.continue': 'Weitersehen',
    'home.section.continueSub': 'Aus deiner Mediathek',
    'home.section.ai': 'KI-Empfehlungen',
    'home.section.aiSub': 'Deine persönlichen Highlights',
    'home.section.mood': 'Nach Stimmung',
    'home.section.moodSub': 'Tippe auf eine Stimmung für eine Live-Liste',
    'search.title': 'Suche',
    'search.placeholder': 'Filme, Regisseure, Schauspieler...',
    'search.filters': 'Filter',
    'search.noResults': 'Keine Filme gefunden.',
    'search.back': 'Zurück',
    'chat.welcomeTitle': 'Was schauen wir heute?',
    'chat.welcomeSub': 'Frage nach Stimmung, Regisseur oder einer Filmliste.',
    'chat.inputPlaceholder': 'Frag CineAI, was du schauen sollst...',
    'chat.status.listening': 'Höre zu...',
    'chat.status.online': 'Online',
    'chat.status.fallback': 'Fallback-Modus',
    'chat.status.local': 'Lokale Wiederherstellung aktiv',
    'chat.status.quick': 'Schnelle KI',
    'chat.starter.mood': 'Meine Stimmung',
    'chat.starter.moodPrompt': 'Ich möchte heute Abend etwas Atmosphärisches und Emotionales sehen.',
    'chat.starter.surprise': 'Überrasch mich',
    'chat.starter.surprisePrompt': 'Empfiehl mir Filme, die ich vielleicht nicht erwarte, aber lieben werde.',
    'chat.starter.prestige': 'Prestige-Auswahl',
    'chat.starter.prestigePrompt': 'Zeige mir oscarreife Filme mit exzellenten Drehbüchern.',
    'chat.starter.thrill': 'Hochspannung',
    'chat.starter.thrillPrompt': 'Finde einen packenden Thriller, der sofort fesselt.',
    'chat.starter.worlds': 'Weltenbau',
    'chat.starter.worldsPrompt': 'Schlage mir epische Sci-Fi- oder Fantasy-Welten vor.',
    'chat.starter.hidden': 'Geheimtipps',
    'chat.starter.hiddenPrompt': 'Zeige mir unterschätzte Filme mit großer Wirkung.',
    'chat.history': 'Chat-Verlauf',
    'chat.historySub': 'Setze eine Konversation fort oder lösche alte Threads.',
    'chat.historyEmpty': 'Noch keine Konversationen.',
    'rail.trending-worldwide.title': 'Weltweite Trends',
    'rail.trending-worldwide.subtitle': 'Die meistdiskutierten Filme aktuell',
    'rail.trending-india.title': 'Trends in Indien',
    'rail.trending-india.subtitle': 'Regionale Hits und Publikumslieblinge',
    'rail.hollywood-scifi.title': 'Hollywood Sci-Fi',
    'rail.hollywood-scifi.subtitle': 'Großartige Zukunftsvisionen und spekulative Welten',
    'rail.award-winners.title': 'Preisgekrönte Filme',
    'rail.award-winners.subtitle': 'Gefeierte Filme von globalen Preisverleihungen',
    'rail.hidden-gems.title': 'Geheimtipps',
    'rail.hidden-gems.subtitle': 'Herausragende Filme abseits des Mainstreams',
    'profile.title': 'Film-Identität',
    'profile.badge.premium': 'Premium Pass',
    'profile.badge.guest': 'Gast',
    'profile.stat.saved': 'Gespeichert',
    'profile.stat.chats': 'KI Chats',
    'profile.stat.genres': 'Genres',
    'profile.taste.title': 'KI-Geschmacksprofil',
    'profile.taste.default': 'Dein Geschmacksprofil wächst mit jeder Filmentdeckung.',
    'profile.section.account': 'Konto-Einstellungen',
    'profile.section.preferences': 'Film-Präferenzen',
    'profile.section.support': 'Support & Hilfe',
    'profile.row.editProfile': 'Profil bearbeiten',
    'profile.row.notifications': 'Benachrichtigungen',
    'profile.row.language': 'Spracheinstellungen',
    'profile.row.genres': 'Lieblingsgenres',
    'profile.row.aiPersonality': 'KI-Persönlichkeit',
    'profile.row.region': 'Inhaltsregion',
    'profile.row.faq': 'Hilfe & FAQ',
    'profile.row.privacy': 'Datenschutzrichtlinie',
    'profile.row.terms': 'Nutzungsbedingungen',
    'profile.row.signOut': 'Abmelden',
    'profile.row.signOutSub': 'Beende diese sichere CineAI-Sitzung',
    'profile.version': 'CineAI v3.0 — Powered by Gemma 4',
    'edit.title': 'Profil bearbeiten',
    'edit.fullName': 'Name',
    'edit.username': 'Benutzername',
    'edit.password': 'Passwort',
    'edit.newPassword': 'Neues Passwort (leer lassen für keine Änderung)',
    'edit.save': 'Änderungen speichern',
    'edit.saving': 'Speichert...',
    'edit.success': 'Profil erfolgreich aktualisiert!',
    'edit.errName': 'Name muss mindestens 2 Zeichen lang sein.',
    'edit.errUsername': 'Benutzername muss mindestens 3 Zeichen lang sein.',
    'edit.errPassword': 'Passwort muss mindestens 6 Zeichen lang sein.',
    'notif.title': 'Benachrichtigungen',
    'notif.desc': 'Steuere, wann CineAI dich mit Filmtipps kontaktiert.',
    'notif.rec': 'Neue Empfehlungen',
    'notif.recDesc': 'Erhalte personalisierte Filmtipps von der KI.',
    'notif.trending': 'Trend-Warnungen',
    'notif.trendingDesc': 'Bleibe über aktuelle Kino-Hits auf dem Laufenden.',
    'notif.upcoming': 'Zukünftige Veröffentlichungen',
    'notif.upcomingDesc': 'Erfahre, wenn deine erwarteten Filme erscheinen.',
    'notif.ai': 'KI-Profil-Updates',
    'notif.aiDesc': 'Erfahre, wenn sich dein Geschmacksprofil erweitert.',
    'notif.watchlist': 'Watchlist-Erinnerungen',
    'notif.watchlistDesc': 'Erhalte Erinnerungen an deine gespeicherten Filme.',
    'notif.alerts': 'Neue Inhalte',
    'notif.alertsDesc': 'Erhalte Updates bei neuen Filmen.',
    'lang.title': 'Spracheinstellungen',
    'lang.desc': 'Ändere die globale Sprache der App und des Chatbots.',
    'genres.title': 'Lieblingsgenres',
    'genres.desc': 'Wähle deine Lieblingsgenres aus, um Empfehlungen anzupassen.',
    'genres.save': 'Genres speichern',
    'personality.title': 'KI-Persönlichkeit',
    'personality.desc': 'Wähle das Verhalten und den Ton deines CineAI-Chatbots.',
    'personality.critic.name': 'Filmkritiker',
    'personality.critic.desc': 'Professionelle, leidenschaftliche Reviews zu Regie, Skript und Kamera.',
    'personality.friend.name': 'Lässiger Kumpel',
    'personality.friend.desc': 'Lockere Empfehlungen wie von einem guten Freund beim Heimkino.',
    'personality.expert.name': 'Filmexperte',
    'personality.expert.desc': 'Akademische Analysen zu historischen Kontexten und Querverweisen.',
    'personality.hype.name': 'Hype-Filmfan',
    'personality.hype.desc': 'Hochenergetische Empfehlungen für Action und Spannung.',
    'personality.companion.name': 'Ruhiger Begleiter',
    'personality.companion.desc': 'Einfühlsame Tipps für gemütliche und emotionale Filmabende.',
    'personality.nerd.name': 'Düsterer Filmnerd',
    'personality.nerd.desc': 'Fokus auf Nischenfilme, Psychothriller und anspruchsvollen Horror.',
    'region.title': 'Inhaltsregion',
    'region.desc': 'Passt Trends und Empfehlungen an deine Region an.',
    'region.global': 'Global',
    'region.us': 'Vereinigte Staaten',
    'region.in': 'Indien',
    'region.jp': 'Japan',
    'region.kr': 'Südkorea',
    'faq.title': 'Hilfe & FAQ',
    'faq.search': 'Hilfethemen durchsuchen...',
    'faq.q1': 'Wie funktioniert der Offline-Modus?',
    'faq.a1': 'CineAI wechselt automatisch in den Offline-Modus, falls der Hauptserver nicht erreichbar ist. Du hast weiterhin Zugriff auf deine Listen.',
    'faq.q2': 'Warum ändern sich meine Empfehlungen?',
    'faq.a2': 'Die Vorschläge basieren auf deinen Lieblingsgenres, deiner Region und deinem Chat-Verlauf.',
    'faq.q3': 'Wie arbeitet das lokale Fallback?',
    'faq.a3': 'Bei Netzwerkfehlern (z. B. 502) greift die App auf lokale Speicherdaten zurück, um dir Empfehlungen anzuzeigen.',
    'faq.q4': 'Woher stammen die Trailer?',
    'faq.a4': 'Trailer werden über TMDB-Verknüpfungen geladen. Falls kein Video hinterlegt ist, suchen wir auf YouTube.',
    'faq.q5': 'Wird meine Watchlist synchronisiert?',
    'faq.a5': 'Ja! Wenn du angemeldet bist, wird alles auf Supabase gespeichert. Als Gast bleibt es lokal auf dem Gerät.',
    'faq.q6': 'Welche Limits gelten für Gäste?',
    'faq.a6': 'Du kannst die App und den Chat frei nutzen. Bei einem Gerätewechsel gehen lokale Daten jedoch verloren.',
    'faq.q7': 'Wie nutze ich die Sprachsteuerung?',
    'faq.a7': 'Tippe auf das Mikrofon im Chat, um zu sprechen (erfordert Zugriff auf dein Mikrofon).',
    'support.title': 'CineAI Support',
    'support.contact': 'Kontakt aufnehmen',
    'support.report': 'Problem melden',
    'support.feedback': 'Feedback senden',
    'support.desc': 'Unser Support-Team hilft dir gerne weiter. Wähle eine Kategorie aus.',
    'support.email': 'Deine E-Mail-Adresse',
    'support.subject': 'Betreff',
    'support.message': 'Nachricht',
    'support.submit': 'Absenden',
    'support.submitting': 'Sendet...',
    'support.success': 'Deine Nachricht wurde gesendet! Wir melden uns in Kürze.',
    'support.error': 'Bitte fülle alle Felder korrekt aus.',
    'support.legalTitle': 'Rechtliches',
    'support.privacyDesc': 'Datenschutz steht bei uns an erster Stelle. Deine Suchen und Filmlisten werden niemals an Dritte weitergegeben.',
    'support.termsDesc': 'Mit der Nutzung von CineAI stimmst du den Richtlinien für den privaten Gebrauch der KI-Empfehlungen zu.',
    'auth.guestUpgrade': 'Auf Premium-Konto upgraden',
    'auth.guestUpgradeSub': 'Erstelle ein Konto, um Watchlists und Chats zu sichern.',
  },
  // Hindi Translation
  hi: {
    'tab.home': 'मुख्य',
    'tab.explore': 'खोजें',
    'tab.aiChat': 'सिने AI',
    'tab.saved': 'सुरक्षित',
    'tab.profile': 'प्रोफ़ाइल',
    'home.greeting.morning': 'शुभ प्रभात',
    'home.greeting.afternoon': 'शुभ दोपहर',
    'home.greeting.evening': 'शुभ संध्या',
    'home.brand.ai': 'AI',
    'home.searchPlaceholder': 'फिल्में, शैलियों को खोजें...',
    'home.section.continue': 'देखना जारी रखें',
    'home.section.continueSub': 'आपके इतिहास से',
    'home.section.ai': 'AI सिफारिशें',
    'home.section.aiSub': 'विशेष रूप से चुनी हुई फ़िल्में',
    'home.section.mood': 'मूड के अनुसार',
    'home.section.moodSub': 'लाइव लिस्ट बनाने के लिए मूड पर टैप करें',
    'search.title': 'खोजें',
    'search.placeholder': 'फिल्में, निर्देशक, कलाकार खोजें...',
    'search.filters': 'फ़िल्टर',
    'search.noResults': 'कोई फिल्म नहीं मिली।',
    'search.back': 'पीछे',
    'chat.welcomeTitle': 'आज क्या देखें?',
    'chat.welcomeSub': 'मूड, निर्देशक या शैली के अनुसार फ़िल्में पूछें।',
    'chat.inputPlaceholder': 'सिने AI से पूछें क्या देखें...',
    'chat.status.listening': 'सुन रहा है...',
    'chat.status.online': 'ऑनलाइन',
    'chat.status.fallback': 'बैकअप मोड',
    'chat.status.local': 'स्थानीय रिकवरी सक्रिय',
    'chat.status.quick': 'क्विक AI',
    'chat.starter.mood': 'मेरे मूड के अनुसार',
    'chat.starter.moodPrompt': 'मुझे आज रात कुछ भावनात्मक और खूबसूरत फिल्में चाहिए।',
    'chat.starter.surprise': 'मुझे चौंकाएं',
    'chat.starter.surprisePrompt': 'ऐसी फिल्मों की सिफारिश करें जिनकी मुझे उम्मीद न हो, पर पसंद आएँ।',
    'chat.starter.prestige': 'प्रतिष्ठित फिल्में',
    'chat.starter.prestigePrompt': 'बेहतरीन अभिनय और कहानी वाली पुरस्कार विजेता फिल्में दिखाएं।',
    'chat.starter.thrill': 'उच्च तनाव',
    'chat.starter.thrillPrompt': 'एक ऐसा थ्रिलर खोजें जो पहली ही सीन से ध्यान खींच ले।',
    'chat.starter.worlds': 'काल्पनिक दुनिया',
    'chat.starter.worldsPrompt': 'शानदार साइंस-फिक्शन या फैंटेसी फिल्मों की सिफारिश करें।',
    'chat.starter.hidden': 'छिपे हुए रत्न',
    'chat.starter.hiddenPrompt': 'कम चर्चित पर भावनात्मक रूप से गहरी फिल्में दिखाएं।',
    'chat.history': 'चैट इतिहास',
    'chat.historySub': 'एक बातचीत फिर से शुरू करें या पुराने थ्रेड्स को साफ़ करें।',
    'chat.historyEmpty': 'अभी तक कोई बातचीत नहीं हुई।',
    'rail.trending-worldwide.title': 'वैश्विक रुझान',
    'rail.trending-worldwide.subtitle': 'इस समय सबसे अधिक चर्चित फ़िल्में',
    'rail.trending-india.title': 'भारत में रुझान',
    'rail.trending-india.subtitle': 'क्षेत्रीय फिल्में और लोगों की पसंदीदा',
    'rail.hollywood-scifi.title': 'हॉलीवुड साइंस-फिक्शन',
    'rail.hollywood-scifi.subtitle': 'भविष्य और काल्पनिक दुनिया की फ़िल्में',
    'rail.award-winners.title': 'पुरस्कार विजेता',
    'rail.award-winners.subtitle': 'वैश्विक पुरस्कारों में सम्मानित फ़िल्में',
    'rail.hidden-gems.title': 'छिपे हुए रत्न',
    'rail.hidden-gems.subtitle': 'मुख्यधारा से अलग उच्च श्रेणी की फ़िल्में',
    'profile.title': 'मनोरंजन पहचान',
    'profile.badge.premium': 'प्रीमियम पास',
    'profile.badge.guest': 'अतिथि',
    'profile.stat.saved': 'सुरक्षित',
    'profile.stat.chats': 'AI चैट',
    'profile.stat.genres': 'शैलियां',
    'profile.taste.title': 'AI पसंद प्रोफ़ाइल',
    'profile.taste.default': 'जैसे-जैसे आप सिने AI का उपयोग करेंगे, आपकी प्रोफ़ाइल बेहतर होगी।',
    'profile.section.account': 'खाता पारिस्थितिकी तंत्र',
    'profile.section.preferences': 'सिनेमाई प्राथमिकताएं',
    'profile.section.support': 'सहायता डेस्क',
    'profile.row.editProfile': 'प्रोफ़ाइल बदलें',
    'profile.row.notifications': 'सूचनाएं',
    'profile.row.language': 'भाषा सेटिंग्स',
    'profile.row.genres': 'पसंदीदा शैलियाँ',
    'profile.row.aiPersonality': 'AI व्यक्तित्व',
    'profile.row.region': 'सामग्री क्षेत्र',
    'profile.row.faq': 'सहायता केंद्र और FAQ',
    'profile.row.privacy': 'गोपनीयता नीति',
    'profile.row.terms': 'सेवा की शर्तें',
    'profile.row.signOut': 'लॉग आउट',
    'profile.row.signOutSub': 'इस सुरक्षित सत्र को समाप्त करें',
    'profile.version': 'सिने AI v3.0 — जेम्मा 4 द्वारा संचालित',
    'edit.title': 'प्रोफ़ाइल बदलें',
    'edit.fullName': 'पूरा नाम',
    'edit.username': 'यूज़रनेम',
    'edit.password': 'पासवर्ड',
    'edit.newPassword': 'नया पासवर्ड (पुराना रखने के लिए खाली छोड़ें)',
    'edit.save': 'बदलाव सुरक्षित करें',
    'edit.saving': 'सुरक्षित हो रहा है...',
    'edit.success': 'प्रोफ़ाइल सफलतापूर्वक अपडेट हो गई!',
    'edit.errName': 'नाम कम से कम 2 अक्षरों का होना चाहिए।',
    'edit.errUsername': 'यूज़रनेम कम से कम 3 अक्षरों का होना चाहिए।',
    'edit.errPassword': 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।',
    'notif.title': 'सूचनाएं',
    'notif.desc': 'नियंत्रित करें कि सिने AI आपको नई सिफारिशों की सूचना कब दे।',
    'notif.rec': 'नई सिफारिशें',
    'notif.recDesc': 'कस्टम AI सिफारिशें प्राप्त करें।',
    'notif.trending': 'ट्रेंडिंग सामग्री',
    'notif.trendingDesc': 'वैश्विक बॉक्स ऑफिस हिट्स की जानकारी रखें।',
    'notif.upcoming': 'आगामी रिलीज़',
    'notif.upcomingDesc': 'अपनी पसंदीदा फिल्मों की रिलीज़ की सूचना पाएं।',
    'notif.ai': 'AI प्रोफ़ाइल अपडेट',
    'notif.aiDesc': 'आपकी AI पसंद बदलने पर सूचना पाएं।',
    'notif.watchlist': 'वॉचलिस्ट रिमाइंडर',
    'notif.watchlistDesc': 'सुरक्षित की गई फिल्मों को देखने के रिमाइंडर।',
    'notif.alerts': 'नई फिल्में',
    'notif.alertsDesc': 'नई फिल्में जुड़ने पर सूचनाएं।',
    'lang.title': 'भाषा सेटिंग्स',
    'lang.desc': 'पूरे ऐप और सिने AI चैटबॉट की भाषा बदलें।',
    'genres.title': 'पसंदीदा शैलियाँ',
    'genres.desc': 'अपनी पसंदीदा शैलियाँ चुनें। ये आपकी सिफारिशों को निर्देशित करती हैं।',
    'genres.save': 'शैलियाँ सुरक्षित करें',
    'personality.title': 'AI व्यक्तित्व',
    'personality.desc': 'अपने सिने AI चैटबॉट का बात करने का तरीका चुनें।',
    'personality.critic.name': 'सिनेमाई समीक्षक',
    'personality.critic.desc': 'निर्देशन, छायांकन और पटकथा पर गंभीर राय देने वाला समीक्षक।',
    'personality.friend.name': 'साधारण दोस्त',
    'personality.friend.desc': 'एक दोस्त की तरह बातचीत और आसान फिल्म सिफारिशें।',
    'personality.expert.name': 'फ़िल्म विशेषज्ञ',
    'personality.expert.desc': 'ऐतिहासिक संदर्भ और फिल्म सिद्धांतों के बारे में गहरी समझ।',
    'personality.hype.name': 'उत्साही प्रशंसक',
    'personality.hype.desc': 'रोमांचक एक्शन और सस्पेंस फिल्मों के लिए उच्च ऊर्जा।',
    'personality.companion.name': 'शांत साथी',
    'personality.companion.desc': 'आरामदायक और भावनात्मक फिल्मों की सिफ़ारिशें।',
    'personality.nerd.name': 'डार्क सिनेमा प्रेमी',
    'personality.nerd.desc': 'मनोवैज्ञानिक थ्रिलर और हॉरर फिल्मों पर ध्यान।',
    'region.title': 'सामग्री क्षेत्र',
    'region.desc': 'यह आपके क्षेत्र के अनुसार ट्रेंडिंग फिल्मों को प्रभावित करता है।',
    'region.global': 'वैश्विक',
    'region.us': 'संयुक्त राज्य अमेरिका',
    'region.in': 'भारत',
    'region.jp': 'जापान',
    'region.kr': 'दक्षिण कोरिया',
    'faq.title': 'सहायता और FAQ',
    'faq.search': 'सहायता खोजें...',
    'faq.q1': 'सिने AI ऑनलाइन/ऑफलाइन स्थिति क्या है?',
    'faq.a1': 'सिने AI का सर्वर बंद होने पर यह डिवाइस के ऑफलाइन बैकअप मोड पर चला जाता है ताकि आपका मनोरंजन न रुके।',
    'faq.q2': 'मेरी सिफारिशें क्यों बदलती हैं?',
    'faq.a2': 'ये आपकी पसंदीदा शैली, चुने गए क्षेत्र और चैट के इतिहास पर निर्भर करती हैं।',
    'faq.q3': 'ऑफलाइन बैकअप कैसे काम करता?',
    'faq.a3': 'सर्वर में एरर (जैसे 502) आने पर ऐप ऑफलाइन रिकवरी चालू कर देता है और प्रीलोड डेटा दिखाता है।',
    'faq.q4': 'ट्रेलर कहाँ से आते हैं?',
    'faq.a4': 'ट्रेलर आधिकारिक TMDB और IMDB डेटाबेस से लिए जाते हैं। यदि ट्रेलर नहीं मिलता है, तो यह YouTube पर खोजता है।',
    'faq.q5': 'क्या मेरी वॉचलिस्ट सिंक होती है?',
    'faq.a5': 'हाँ! यदि आप लॉग इन हैं तो यह Supabase पर सिंक होता है। अन्यथा डिवाइस पर सुरक्षित रहता है।',
    'faq.q6': 'अतिथि मोड की सीमाएं क्या हैं?',
    'faq.a6': 'आप चैट और खोज कर सकते हैं, लेकिन ऐप डेटा डिलीट करने पर आपकी लिस्ट खो जाएगी।',
    'faq.q7': 'आवाज से कैसे खोजें?',
    'faq.a7': 'चैट में माइक पर टैप करके बोलें, यह आपकी आवाज़ को टेक्स्ट में बदल देगा (माइक अनुमति आवश्यक)।',
    'support.title': 'सिने AI सहायता',
    'support.contact': 'संपर्क करें',
    'support.report': 'समस्या रिपोर्ट करें',
    'support.feedback': 'प्रतिक्रिया दें',
    'support.desc': 'हमारी टीम आपकी सहायता के लिए तैयार है। श्रेणी चुनें।',
    'support.email': 'आपका ईमेल पता',
    'support.subject': 'विषय',
    'support.message': 'विवरण',
    'support.submit': 'जमा करें',
    'support.submitting': 'भेज रहा है...',
    'support.success': 'आपका टिकट भेज दिया गया है! हम जल्द ही संपर्क करेंगे।',
    'support.error': 'कृपया सभी फ़ील्ड सही तरीके से भरें।',
    'support.legalTitle': 'कानूनी केंद्र',
    'support.privacyDesc': 'आपकी गोपनीयता हमारी प्राथमिकता है। हम आपका खोज इतिहास किसी के साथ साझा नहीं करते।',
    'support.termsDesc': 'सिने AI का उपयोग करके आप व्यक्तिगत मनोरंजन के लिए इसकी सिफारिशों के उपयोग की शर्तों को स्वीकार करते हैं।',
    'auth.guestUpgrade': 'प्रीमियम खाते में अपग्रेड करें',
    'auth.guestUpgradeSub': 'वॉचलिस्ट और चैट सुरक्षित करने के लिए खाता बनाएं।',
  },
  // Japanese Translation
  ja: {
    'tab.home': 'ホーム',
    'tab.explore': '見つける',
    'tab.aiChat': 'シネ AI',
    'tab.saved': '保存済み',
    'tab.profile': 'マイページ',
    'home.greeting.morning': 'おはようございます',
    'home.greeting.afternoon': 'こんにちは',
    'home.greeting.evening': 'こんばんは',
    'home.brand.ai': 'AI',
    'home.searchPlaceholder': '映画やジャンルを検索...',
    'home.section.continue': '視聴を再開',
    'home.section.continueSub': '最近見た映画',
    'home.section.ai': 'AIのおすすめ',
    'home.section.aiSub': '高精度なセレクト作品',
    'home.section.mood': '気分で探す',
    'home.section.moodSub': '気分をタップしてリアルタイムリストを生成',
    'search.title': '検索',
    'search.placeholder': '映画、監督、キャストを検索...',
    'search.filters': 'フィルター',
    'search.noResults': '該当する映画が見つかりませんでした。',
    'search.back': '戻る',
    'chat.welcomeTitle': '何を見ましょうか？',
    'chat.welcomeSub': '気分や監督、ジャンルなど、何でもシネ AIに聞いてみてください。',
    'chat.inputPlaceholder': 'シネAIにおすすめを聞く...',
    'chat.status.listening': '聞き取り中...',
    'chat.status.online': 'オンライン',
    'chat.status.fallback': 'ローカル',
    'chat.status.local': 'ローカル復旧モード有効',
    'chat.status.quick': '高速 AI',
    'chat.starter.mood': '気分に合わせる',
    'chat.starter.moodPrompt': '今夜は情緒的で美しい映像の映画が見たいです。',
    'chat.starter.surprise': 'サプライズを',
    'chat.starter.surprisePrompt': '意外だけど絶対に好きになるような映画を教えて。',
    'chat.starter.prestige': '名作セレクト',
    'chat.starter.prestigePrompt': '脚本や演技が素晴らしい、評価の高い名作を教えて。',
    'chat.starter.thrill': '緊迫のサスペンス',
    'chat.starter.thrillPrompt': '最初から最後まで目が離せないスリリングな映画。',
    'chat.starter.worlds': '別世界への没入',
    'chat.starter.worldsPrompt': '壮大なSFやファンタジーの世界観を持つおすすめ作品。',
    'chat.starter.hidden': '隠れた名作',
    'chat.starter.hiddenPrompt': '評価は控えめだけど感動する、知る人ぞ知る名作。',
    'chat.history': 'チャット履歴',
    'chat.historySub': '会話を再開するか、古いスレッドをクリアします。',
    'chat.historyEmpty': '会話はまだありません。',
    'rail.trending-worldwide.title': '世界トレンド',
    'rail.trending-worldwide.subtitle': '今最も話題の映画',
    'rail.trending-india.title': 'インド国内トレンド',
    'rail.trending-india.subtitle': '地域のトレンドと人気作品',
    'rail.hollywood-scifi.title': 'ハリウッド SF',
    'rail.hollywood-scifi.subtitle': '壮大な未来と空想の世界',
    'rail.award-winners.title': '受賞作セレクト',
    'rail.award-winners.subtitle': '世界中の映画賞で称賛された名作',
    'rail.hidden-gems.title': '隠れた名作',
    'rail.hidden-gems.subtitle': '主流から外れた高評価の隠れた傑作',
    'profile.title': 'エンタメ ID',
    'profile.badge.premium': 'プレミアムパス',
    'profile.badge.guest': 'ゲスト',
    'profile.stat.saved': '保存済み',
    'profile.stat.chats': 'AIチャット',
    'profile.stat.genres': 'ジャンル',
    'profile.taste.title': 'AI分析の好み',
    'profile.taste.default': 'シネ AIと話すほど、あなた好みのプロフィールが成長します。',
    'profile.section.account': 'アカウント設定',
    'profile.section.preferences': 'シネマ設定',
    'profile.section.support': 'サポートデスク',
    'profile.row.editProfile': 'プロフィール編集',
    'profile.row.notifications': '通知センター',
    'profile.row.language': '言語設定',
    'profile.row.genres': 'お気に入りジャンル',
    'profile.row.aiPersonality': 'AIキャラクター設定',
    'profile.row.region': '対象地域',
    'profile.row.faq': 'ヘルプとFAQ',
    'profile.row.privacy': 'プライバシーポリシー',
    'profile.row.terms': '利用規約',
    'profile.row.signOut': 'ログアウト',
    'profile.row.signOutSub': '安全にセッションを終了します',
    'profile.version': 'CineAI v3.0 — Powered by Gemma 4',
    'edit.title': 'プロフィール編集',
    'edit.fullName': '名前',
    'edit.username': 'ユーザー名',
    'edit.password': 'パスワード',
    'edit.newPassword': '新しいパスワード（変更しない場合は空欄）',
    'edit.save': '変更を保存',
    'edit.saving': '保存中...',
    'edit.success': 'プロフィールを更新しました！',
    'edit.errName': '名前は2文字以上で入力してください。',
    'edit.errUsername': 'ユーザー名は3文字以上で入力してください。',
    'edit.errPassword': 'パスワードは6文字以上で入力してください。',
    'notif.title': '通知設定',
    'notif.desc': 'おすすめ映画や最新情報を受け取る設定を管理します。',
    'notif.rec': '新しいおすすめ映画',
    'notif.recDesc': 'あなた好みにパーソナライズされたAIおすすめ映画。',
    'notif.trending': 'トレンド情報',
    'notif.trendingDesc': '世界中の話題作やヒット情報を受け取る。',
    'notif.upcoming': 'もうすぐ公開の作品',
    'notif.upcomingDesc': 'お気に入り映画の公開時にお知らせ。',
    'notif.ai': 'AIプロフィール更新',
    'notif.aiDesc': 'あなたの好みの変化が分析されたときにお知らせ。',
    'notif.watchlist': 'ウォッチリストのリマインダー',
    'notif.watchlistDesc': '保存した作品を見るためのおすすめリマインド。',
    'notif.alerts': '新着コンテンツ',
    'notif.alertsDesc': '新しい映画が追加されたときにお知らせ。',
    'lang.title': '言語設定',
    'lang.desc': 'アプリ全体およびAIチャットで使用する言語を変更します。',
    'genres.title': 'お気に入りジャンル',
    'genres.desc': 'お気に入りの映画ジャンルを選択します。おすすめ表示やAIの回答に影響します。',
    'genres.save': 'ジャンルを保存',
    'personality.title': 'AIキャラクター設定',
    'personality.desc': 'シネAIチャットボットの話す口調や性格を選べます。',
    'personality.critic.name': '映画評論家',
    'personality.critic.desc': '専門的で温かみがあり、演出や脚本、撮影技術にこだわる評論家。',
    'personality.friend.name': 'いつもの友達',
    'personality.friend.desc': 'ポップコーンを食べながら話すような、親しみやすく飾らない友達。',
    'personality.expert.name': '映画オタク',
    'personality.expert.desc': '歴史的背景や映画理論、隠れたつながりなどを熱弁するオタク。',
    'personality.hype.name': '熱血ファン',
    'personality.hype.desc': 'ハイテンションでアクションやスリル満点な作品を熱烈に薦めるファン。',
    'personality.companion.name': '癒しの案内人',
    'personality.companion.desc': '心温まるヒューマンドラマや心地よい映画を静かに薦める案内人。',
    'personality.nerd.name': 'ダークシネマニア',
    'personality.nerd.desc': '心理スリラーやインディーズホラーなど、少し暗くてディープなジャンルに強い。',
    'region.title': '対象地域',
    'region.desc': 'トレンドやおすすめ映画の国別対象地域を変更します。',
    'region.global': 'グローバル',
    'region.us': 'アメリカ',
    'region.in': 'インド',
    'region.jp': '日本',
    'region.kr': '韓国',
    'faq.title': 'ヘルプとFAQ',
    'faq.search': 'ヘルプを検索...',
    'faq.q1': 'CineAIのオンライン/オフライン状態とは何ですか？',
    'faq.a1': 'サーバーがダウンしている場合、CineAIは自動的にデバイス内のローカルAIモードに切り替わり、チャット機能を維持します。',
    'faq.q2': 'おすすめの映画が変わるのはなぜですか？',
    'faq.a2': 'ジャンル設定、対象地域、そしてAIとの会話履歴に基づいてリアルタイムに更新されます。',
    'faq.q3': 'オフラインモードはどのように機能しますか？',
    'faq.a3': '接続エラー（502など）が発生すると、アプリはキャッシュされたデータを利用し、オフラインおすすめを表示します。',
    'faq.q4': '予告編（トレーラー）はどこから取得されますか？',
    'faq.a4': 'TMDBおよびIMDBの公式動画をロードします。見つからない場合は自動的にYouTubeを検索します。',
    'faq.q5': 'ウォッチリストは同期されますか？',
    'faq.a5': 'はい、ログインしている場合はSupabaseに自動同期されます。ゲストの場合は端末内にのみ保存されます。',
    'faq.q6': 'ゲストモードの制限は何ですか？',
    'faq.a6': 'チャットや検索は使えますが、アプリのアンインストール等でデータが消えてしまいます。',
    'faq.q7': '音声で入力するには？',
    'faq.a7': 'チャットのマイクアイコンをタップして話してください。音声を自動でテキストにします。',
    'support.title': 'シネAI サポート',
    'support.contact': 'お問い合わせ',
    'support.report': '問題を報告',
    'support.feedback': 'フィードバック送信',
    'support.desc': 'お困りの際は、カテゴリーを選んでサポートチームにお送りください。',
    'support.email': 'メールアドレス',
    'support.subject': '件名',
    'support.message': '本文',
    'support.submit': '送信する',
    'support.submitting': '送信中...',
    'support.success': '問い合わせを送信しました！間もなく返信いたします。',
    'support.error': '入力情報が正しくありません。ご確認ください。',
    'support.legalTitle': 'リーガルセンター',
    'support.privacyDesc': 'お客様のプライバシーは厳重に守られています。検索履歴やチャットは外部に公開されません。',
    'support.termsDesc': 'シネAIのご利用により、お客様は非営利の娯楽目的でAI機能を使用することに同意したものとみなされます。',
    'auth.guestUpgrade': 'プレミアムアカウントへ登録',
    'auth.guestUpgradeSub': 'ウォッチリストやチャット履歴を保存するために登録します。',
  },
  // Korean Translation
  ko: {
    'tab.home': '홈',
    'tab.explore': '둘러보기',
    'tab.aiChat': '시네 AI',
    'tab.saved': '저장됨',
    'tab.profile': '프로필',
    'home.greeting.morning': '좋은 아침입니다',
    'home.greeting.afternoon': '안녕하세요',
    'home.greeting.evening': '즐거운 저녁입니다',
    'home.brand.ai': 'AI',
    'home.searchPlaceholder': '영화, 장르 검색...',
    'home.section.continue': '이어 보기',
    'home.section.continueSub': '최근 시청 목록',
    'home.section.ai': 'AI 추천 영화',
    'home.section.aiSub': '높은 정확도의 맞춤작',
    'home.section.mood': '감정별 영화',
    'home.section.moodSub': '감정을 선택해 실시간 추천을 생성하세요',
    'search.title': '검색',
    'search.placeholder': '영화, 감독, 배우 검색...',
    'search.filters': '필터',
    'search.noResults': '해당하는 영화를 찾을 수 없습니다.',
    'search.back': '뒤로',
    'chat.welcomeTitle': '오늘 무엇을 볼까요?',
    'chat.welcomeSub': '기분, 감독, 장르 등 무엇이든 시네 AI에 물어보세요.',
    'chat.inputPlaceholder': '시네AI에게 볼만한 영화 물어보기...',
    'chat.status.listening': '듣고 있습니다...',
    'chat.status.online': '온라인',
    'chat.status.fallback': '로컬 모드',
    'chat.status.local': '로컬 복구 기능 활성화',
    'chat.status.quick': '빠른 AI',
    'chat.starter.mood': '기분에 맞춰서',
    'chat.starter.moodPrompt': '오늘 밤은 영상미가 아름답고 감성적인 영화가 보고 싶어요.',
    'chat.starter.surprise': '깜짝 추천',
    'chat.starter.surprisePrompt': '기대하지 않았지만 절대적으로 좋아하게 될 영화를 추천해줘.',
    'chat.starter.prestige': '웰메이드 명작',
    'chat.starter.prestigePrompt': '각본과 연기력이 뛰어난 명작 영화를 알려줘.',
    'chat.starter.thrill': '숨 막히는 서스펜스',
    'chat.starter.thrillPrompt': '첫 장면부터 몰입되는 팽팽한 스릴러 영화.',
    'chat.starter.worlds': '가상 세계 몰입',
    'chat.starter.worldsPrompt': '세계관이 웅장한 SF나 판타지 영화 추천.',
    'chat.starter.hidden': '숨겨진 보석',
    'chat.starter.hiddenPrompt': '대중성은 낮지만 감동이 깊은 명작 영화.',
    'chat.history': '채팅 기록',
    'chat.historySub': '대화를 재개하거나 오래된 스레드를 지웁니다.',
    'chat.historyEmpty': '아직 대화가 없습니다.',
    'rail.trending-worldwide.title': '글로벌 인기작',
    'rail.trending-worldwide.subtitle': '지금 가장 화제가 되는 영화',
    'rail.trending-india.title': '인도 인기작',
    'rail.trending-india.subtitle': '지역 인기 영화 및 추천작',
    'rail.hollywood-scifi.title': '할리우드 SF',
    'rail.hollywood-scifi.subtitle': '웅장한 미래와 상상의 세계',
    'rail.award-winners.title': '수상작 컬렉션',
    'rail.award-winners.subtitle': '세계 주요 영화제 수상작',
    'rail.hidden-gems.title': '숨겨진 보석',
    'rail.hidden-gems.subtitle': '대중적이지 않지만 평점이 높은 명작',
    'profile.title': '콘텐츠 프로필',
    'profile.badge.premium': '프리미엄 패스',
    'profile.badge.guest': '게스트',
    'profile.stat.saved': '저장됨',
    'profile.stat.chats': 'AI 채팅',
    'profile.stat.genres': '장르',
    'profile.taste.title': 'AI 취향 분석',
    'profile.taste.default': '시네 AI와 많은 대화를 나눌수록 프로필 분석이 정교해집니다.',
    'profile.section.account': '계정 생태계',
    'profile.section.preferences': '시네마 설정',
    'profile.section.support': '고객 지원',
    'profile.row.editProfile': '프로필 편집',
    'profile.row.notifications': '알림 센터',
    'profile.row.language': '언어 설정',
    'profile.row.genres': '선호 장르',
    'profile.row.aiPersonality': 'AI 성격 설정',
    'profile.row.region': '콘텐츠 지역',
    'profile.row.faq': '도움말 & FAQ',
    'profile.row.privacy': '개인정보 처리방침',
    'profile.row.terms': '이용 약관',
    'profile.row.signOut': '로그아웃',
    'profile.row.signOutSub': '안전하게 세션을 종료합니다',
    'profile.version': 'CineAI v3.0 — Powered by Gemma 4',
    'edit.title': '프로필 편집',
    'edit.fullName': '이름',
    'edit.username': '사용자 이름',
    'edit.password': '비밀번호',
    'edit.newPassword': '새 비밀번호 (기존 번호 유지는 공란)',
    'edit.save': '변경사항 저장',
    'edit.saving': '저장 중...',
    'edit.success': '프로필이 정상적으로 수정되었습니다!',
    'edit.errName': '이름은 최소 2글자 이상이어야 합니다.',
    'edit.errUsername': '사용자 이름은 최소 3글자 이상이어야 합니다.',
    'edit.errPassword': '비밀번호는 최소 6글자 이상이어야 합니다.',
    'notif.title': '알림 센터',
    'notif.desc': '추천 영화나 최신작 소식을 받는 알림 옵션을 구성합니다.',
    'notif.rec': '새로운 추천 영화',
    'notif.recDesc': '내 취향에 딱 맞춘 커스텀 AI 추천 알림.',
    'notif.trending': '트렌드 영화',
    'notif.trendingDesc': '글로벌 박스오피스 화제작 소식 알림.',
    'notif.upcoming': '개봉 예정작',
    'notif.upcomingDesc': '기대 중인 영화 개봉일 알림.',
    'notif.ai': 'AI 취향 데이터 업데이트',
    'notif.aiDesc': '취향 분석이 정교해졌을 때 업데이트 알림.',
    'notif.watchlist': '저장한 영화 리마인더',
    'notif.watchlistDesc': '감상하지 않은 저장작을 보는 유도 알림.',
    'notif.alerts': '신규 추가 알림',
    'notif.alertsDesc': '영화가 신규 등록되었을 때 알림.',
    'lang.title': '언어 설정',
    'lang.desc': '앱 전반 및 AI 챗봇과 대화할 때 사용하는 언어를 변경합니다.',
    'genres.title': '선호 장르',
    'genres.desc': '좋아하는 영화 장르를 선택해 영화 추천 결과를 최적화하세요.',
    'genres.save': '장르 저장',
    'personality.title': 'AI 성격 설정',
    'personality.desc': '시네AI 대화 상대의 말투와 성향을 선택해 보세요.',
    'personality.critic.name': '시네마 평론가',
    'personality.critic.desc': '전문적이고 깊이 있는 연출, 각본, 영상미를 따지는 깐깐한 평론가.',
    'personality.friend.name': '친근한 친구',
    'personality.friend.desc': '팝콘 먹으며 영화 수다 떠는 편하고 편견 없는 내 친구.',
    'personality.expert.name': '영화 전문가',
    'personality.expert.desc': '영화 역사, 이론, 숨은 연결고리를 세세히 짚어주는 딥 오타쿠.',
    'personality.hype.name': '열정적인 추천가',
    'personality.hype.desc': '액션과 숨 막히는 스릴러 등 짜릿한 영화를 목청껏 추천하는 에너자이저.',
    'personality.companion.name': '차분한 길잡이',
    'personality.companion.desc': '마음이 몽글몽글해지는 인생작과 감동 영화를 조용히 짚어주는 힐러.',
    'personality.nerd.name': '다크 시네마 오타쿠',
    'personality.nerd.desc': '그로테스크한 인디 스릴러, 서스펜스, 공포 전문 마니아.',
    'region.title': '콘텐츠 지역',
    'region.desc': '국가별 트렌드 지수와 맞춤 추천의 지역 설정을 변경합니다.',
    'region.global': '글로벌',
    'region.us': '미국',
    'region.in': '인도',
    'region.jp': '일본',
    'region.kr': '대한민국',
    'faq.title': '도움말 & FAQ',
    'faq.search': '자주 묻는 질문 검색...',
    'faq.q1': 'CineAI 온라인/오프라인 모드는 무엇인가요?',
    'faq.a1': '서버의 연결 상태가 불안정하거나 Render 컨테이너 점검 시, 시네AI는 단절 없이 기기 로컬 인공지능 모드로 즉각 복구 작동합니다.',
    'faq.q2': '추천 영화 목록이 자꾸 바뀌는 이유는 무엇인가요?',
    'faq.a2': '선호 장르 설정, 지역 옵션, 그리고 AI와의 최근 채팅 문맥을 종합 연산하여 끊임없이 진화합니다.',
    'faq.q3': '오프라인 인공지능 복구는 어떻게 작동하나요?',
    'faq.a3': '네트워크 오류(예: 502 Bad Gateway) 발생 시 앱이 캐시 테이블을 읽어 오프라인 추천 카드를 자연스럽게 노출합니다.',
    'faq.q4': '예고편 정보는 어디서 오나요?',
    'faq.a4': 'TMDB에 등록된 공식 비디오 중 IMDB 코드와 매칭되는 최상의 링크를 로드합니다. 없을 시 유튜브로 대체 검색합니다.',
    'faq.q5': '저장 목록은 연동되나요?',
    'faq.a5': '로그인 회원 정보가 있다면 Supabase에 실시간 연동되며, 게스트 상태에선 단말에 안전하게 로컬 저장됩니다.',
    'faq.q6': '게스트 계정의 단점은 무엇인가요?',
    'faq.a6': '대부분의 기능을 동일하게 쓸 수 있지만 앱 삭제나 기기 초기화 시 저장된 리스트가 삭제될 수 있습니다.',
    'faq.q7': '음성 음성 입력 기능은 어떻게 작동하나요?',
    'faq.a7': '대화 창 마이크 아이콘을 누르고 말을 하시면 텍스트로 받아쓰기가 실행됩니다 (마이크 권한 필요).',
    'support.title': '시네AI 지원 센터',
    'support.contact': '문의하기',
    'support.report': '오류 제보',
    'support.feedback': '피드백 건의',
    'support.desc': '개발팀이 귀하의 건의사항과 에러 리포트를 직접 검토합니다. 카테고리를 선택 후 작성해 주세요.',
    'support.email': '이메일 주소',
    'support.subject': '제목',
    'support.message': '상세 내용',
    'support.submit': '제출하기',
    'support.submitting': '제출 중...',
    'support.success': '문의가 정상 접수되었습니다! 신속히 피드백 드리겠습니다.',
    'support.error': '모든 입력란을 양식에 맞게 입력해 주세요.',
    'support.legalTitle': '법률 및 이용 규정',
    'support.privacyDesc': '사용자의 개인정보는 강력히 보호됩니다. 대화 내역이나 영화 관심 로그를 절대 3자에게 판매/제공하지 않습니다.',
    'support.termsDesc': '시네AI는 비영리 개인적 엔터테인먼트 목적으로만 이용할 수 있습니다. 엔드포인트 공격 방지 차원의 SlowAPI가 가동됩니다.',
    'auth.guestUpgrade': '프리미엄 계정으로 업그레이드',
    'auth.guestUpgradeSub': '저장한 영화와 대화 이력을 안전하게 영구 저장하세요.',
  },
};

interface LanguageState {
  language: LanguageCode;
  setLanguage: (language: LanguageCode) => Promise<void>;
  loadLanguage: () => Promise<void>;
  t: (key: string) => string;
}

export const useLanguageStore = create<LanguageState>((set, get) => ({
  language: 'en',
  
  setLanguage: async (language: LanguageCode) => {
    try {
      await AsyncStorage.setItem('preferredLanguage', language);
      set({ language });
    } catch (e) {
      console.error('Failed to save language setting:', e);
    }
  },
  
  loadLanguage: async () => {
    try {
      const saved = await AsyncStorage.getItem('preferredLanguage');
      if (saved && (saved in TRANSLATIONS)) {
        set({ language: saved as LanguageCode });
      }
    } catch (e) {
      console.error('Failed to load language setting:', e);
    }
  },
  
  t: (key: string) => {
    const lang = get().language;
    const translations = TRANSLATIONS[lang] || TRANSLATIONS.en;
    return translations[key] || TRANSLATIONS.en[key] || key;
  },
}));
