from fastapi import Depends, HTTPException, status
from fastapi.security import OAuth2PasswordBearer
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select
from typing import Optional
from app.db.session import get_db
from app.core.security import decode_token
from app.models.user import User

# Standard OAuth2 scheme pointing to our login endpoint for autogenerated docs.
# auto_error=False lets guest-safe endpoints decide whether auth is required.
oauth2_scheme = OAuth2PasswordBearer(tokenUrl="/api/v1/auth/login", auto_error=False)

async def get_current_user(
    token: Optional[str] = Depends(oauth2_scheme),
    db: AsyncSession = Depends(get_db)
) -> User:
    """Dependency validating the Access Token and returning the current authenticated User model."""
    credentials_exception = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Could not validate credentials",
        headers={"WWW-Authenticate": "Bearer"},
    )

    if not token:
        raise credentials_exception
    
    # Decrypt and parse access token payload
    payload = decode_token(token)
    user_id = payload.get("sub")
    if not user_id:
        raise credentials_exception
        
    # Fetch user details
    query = select(User).where(User.id == user_id)
    result = await db.execute(query)
    user = result.scalars().first()
    
    if not user:
        raise credentials_exception
        
    return user

async def get_optional_user(
    token: Optional[str] = Depends(oauth2_scheme),
    db: AsyncSession = Depends(get_db)
) -> Optional[User]:
    """Dependency attempting to validate user but returning None instead of failing if not authenticated (useful for Guest access)."""
    if not token:
        return None

    try:
        user = await get_current_user(token, db)
        return user
    except HTTPException:
        return None
